import { db, carts } from "./index";
import dotenv from "dotenv";

dotenv.config();

const initialCarts = [
  {
    email: "sarah.m@gmail.com",
    cartValue: 120.00,
    productName: "Leather Tote Bag",
    customerTier: "Gold",
    frictionPoint: "Price",
    strategy: "Discount",
    status: "Converted",
    confidenceScore: 0.89,
    agentLog: "Customer has a high cart value ($120.00) and is a Gold tier member. Friction point detected as Price due to coupon code search behavior. Margins allow for a 15% discount. Selected 'Discount' strategy to incentivize immediate purchase.",
    emailCopy: "Hi Sarah, we noticed you left something special in your cart. To help you make it yours, here is a 15% discount code: SAVE15. Valid for the next 24 hours!",
    createdAt: new Date(Date.now() - 4 * 3600000), // 4 hours ago
  },
  {
    email: "james.k@outlook.com",
    cartValue: 45.50,
    productName: "Wireless Earbuds",
    customerTier: "Bronze",
    frictionPoint: "Shipping Cost",
    strategy: "Reminder",
    status: "Sent",
    confidenceScore: 0.72,
    agentLog: "Bronze tier customer with moderate cart value ($45.50). Left during shipping options page. Margin is too low for discount. Selected 'Reminder' strategy to gently nudge them, highlighting free shipping threshold.",
    emailCopy: "Hey James, you left your Wireless Earbuds behind. Just a heads up that your order qualifies for free standard shipping if you add any small accessory, or you can complete your checkout now!",
    createdAt: new Date(Date.now() - 6 * 3600000),
  },
  {
    email: "vip.buyer@corporate.com",
    cartValue: 450.00,
    productName: "Ergonomic Office Chair",
    customerTier: "VIP",
    frictionPoint: "Trust",
    strategy: "Social Proof",
    status: "Converted",
    confidenceScore: 0.95,
    agentLog: "VIP customer with very high cart value ($450.00). Left at payment method screen, indicating security or trust concerns. Margins are high but customer values reliability. Selected 'Social Proof' highlighting lifetime warranty and 5-star corporate reviews.",
    emailCopy: "Hello there, we noticed you did not complete your checkout for the Ergonomic Office Chair. Did you know it is backed by our 10-year warranty and has been rated 4.9/5 stars by over 500 office professionals? Read what others are saying...",
    createdAt: new Date(Date.now() - 10 * 3600000),
  },
  {
    email: "emily.rose@yahoo.com",
    cartValue: 85.00,
    productName: "Summer Floral Dress",
    customerTier: "Silver",
    frictionPoint: "Price",
    strategy: "Scarcity",
    status: "Failed",
    confidenceScore: 0.78,
    agentLog: "Silver tier customer with $85.00 cart. Product has low stock (only 3 left in inventory). Selected 'Scarcity' strategy to highlight high demand and limited stock without diluting margins.",
    emailCopy: "Hi Emily, the Summer Floral Dress in your cart is selling fast! There are only 3 left in stock, and another shopper has it in their cart right now. Complete your checkout to secure yours before it is gone.",
    createdAt: new Date(Date.now() - 24 * 3600000),
  },
  {
    email: "david.lee@hotmail.com",
    cartValue: 35.00,
    productName: "Stainless Steel Water Bottle",
    customerTier: "Bronze",
    frictionPoint: "Technical Error",
    strategy: "Reminder",
    status: "Converted",
    confidenceScore: 0.81,
    agentLog: "Bronze customer with $35.00 cart. Session terminated abruptly during checkout, suggesting a potential Technical Error. Selected 'Reminder' to offer support and pre-fill their cart link.",
    emailCopy: "Hi David, it looks like your checkout session may have been interrupted. No worries—we saved your cart! Click here to easily resume your order for the Stainless Steel Water Bottle. Need help? Just reply to this email.",
    createdAt: new Date(Date.now() - 12 * 3600000),
  },
  {
    email: "michael.s@live.com",
    cartValue: 150.00,
    productName: "Mechanical Gaming Keyboard",
    customerTier: "Gold",
    frictionPoint: "Trust",
    strategy: "Social Proof",
    status: "Sent",
    confidenceScore: 0.88,
    agentLog: "Gold customer, high cart value ($150.00). Selected 'Social Proof' to highlight glowing reviews from the gaming community, reinforcing product quality and brand trust.",
    emailCopy: "Hey Michael, we saved your Mechanical Gaming Keyboard. Check out what pro esports players are saying about its ultra-responsive switches: 'The best keyboard I've owned in a decade.' - Alex P. Finish your setup today!",
    createdAt: new Date(Date.now() - 2 * 3600000),
  },
  {
    email: "jessica.a@gmail.com",
    cartValue: 65.00,
    productName: "Organic Skincare Set",
    customerTier: "Silver",
    frictionPoint: "Price",
    strategy: "Discount",
    status: "Converted",
    confidenceScore: 0.84,
    agentLog: "Silver customer, moderate value. Cart abandoned at discount input field. Selected 'Discount' with a conservative 10% off to nudged them to convert while preserving margins.",
    emailCopy: "Hi Jessica, we noticed you left the Organic Skincare Set behind. Here is a 10% discount to help you get started: SKIN10. Enter it at checkout to claim your savings!",
    createdAt: new Date(Date.now() - 18 * 3600000),
  },
  {
    email: "robert.t@yahoo.com",
    cartValue: 280.00,
    productName: "Noise-Cancelling Headphones",
    customerTier: "VIP",
    frictionPoint: "Price",
    strategy: "Discount",
    status: "Converted",
    confidenceScore: 0.92,
    agentLog: "VIP customer with high-margin items ($280.00). Selected 'Discount' (15% off) because of high VIP LTV and willingness to convert. High confidence.",
    emailCopy: "Dear Robert, as a valued VIP member, we want to make sure you get the best deal on the Noise-Cancelling Headphones. Use code VIP15 at checkout for an exclusive 15% off your order today.",
    createdAt: new Date(Date.now() - 36 * 3600000),
  },
  {
    email: "clara.v@gmail.com",
    cartValue: 55.00,
    productName: "Yoga Mat & Block Set",
    customerTier: "Bronze",
    frictionPoint: "Price",
    strategy: "Scarcity",
    status: "Failed",
    confidenceScore: 0.65,
    agentLog: "Bronze customer, moderate cart. Stock of Yoga Mat is critical. Selected 'Scarcity' over discount to avoid margin erosion on a high-demand item.",
    emailCopy: "Hi Clara, items in your cart are in high demand! Our Yoga Mat & Block Set is currently running extremely low on stock. Reserve yours now by completing your checkout.",
    createdAt: new Date(Date.now() - 48 * 3600000),
  },
  {
    email: "daniel.g@outlook.com",
    cartValue: 195.00,
    productName: "Smart Thermostat",
    customerTier: "Gold",
    frictionPoint: "Shipping Cost",
    strategy: "Reminder",
    status: "Converted",
    confidenceScore: 0.87,
    agentLog: "Gold customer, high cart value ($195.00). Left at shipping screen. Highlighted that they automatically qualify for free expedited shipping due to order value.",
    emailCopy: "Hi Daniel, did you forget your Smart Thermostat? Good news: since your cart is over $150, you qualify for free 2-day express shipping! Complete your order now and have it on your doorstep in no time.",
    createdAt: new Date(Date.now() - 14 * 3600000),
  },
  {
    email: "alex.m@gmail.com",
    cartValue: 70.00,
    productName: "Running Shoes",
    customerTier: "Silver",
    frictionPoint: "Price",
    strategy: "Social Proof",
    status: "Sent",
    confidenceScore: 0.79,
    agentLog: "Silver customer. Left after viewing reviews page. Selected 'Social Proof' to highlight the 30-day money-back guarantee and running magazine accolades.",
    emailCopy: "Hi Alex, still thinking about those Running Shoes? Try them risk-free with our 30-day return policy. Plus, Runner's World just named them 'Best Comfort Shoe of 2026'. Buy with confidence!",
    createdAt: new Date(Date.now() - 1 * 3600000),
  },
  {
    email: "nathan.d@live.com",
    cartValue: 320.00,
    productName: "Robot Vacuum Cleaner",
    customerTier: "VIP",
    frictionPoint: "Technical Error",
    strategy: "Reminder",
    status: "Converted",
    confidenceScore: 0.90,
    agentLog: "VIP customer, high cart value. Checkout crashed during payment processing. Selected 'Reminder' with direct personal customer service outreach to guarantee a VIP experience.",
    emailCopy: "Hello Nathan, we saw that you experienced an issue while completing your checkout for the Robot Vacuum Cleaner. Our VIP concierge team is standing by to assist you. Simply reply to this email or call us at 1-800-RECOVER.",
    createdAt: new Date(Date.now() - 8 * 3600000),
  },
  {
    email: "sofia.r@yahoo.com",
    cartValue: 40.00,
    productName: "Ceramic Coffee Mug",
    customerTier: "Bronze",
    frictionPoint: "Price",
    strategy: "Reminder",
    status: "Failed",
    confidenceScore: 0.60,
    agentLog: "Bronze customer, low cart value. Selected 'Reminder' to avoid discounting, but conversion probability is low due to price sensitivity on low-margin item.",
    emailCopy: "Hi Sofia, we noticed you left the Ceramic Coffee Mug in your cart. We have saved it for you! Feel free to complete your order whenever you are ready.",
    createdAt: new Date(Date.now() - 72 * 3600000),
  },
  {
    email: "william.h@gmail.com",
    cartValue: 130.00,
    productName: "Outdoor Backpack",
    customerTier: "Silver",
    frictionPoint: "Shipping Cost",
    strategy: "Scarcity",
    status: "Converted",
    confidenceScore: 0.83,
    agentLog: "Silver customer, moderate-to-high cart. Stock is limited for this color. Selected 'Scarcity' strategy to drive urgency, noting that free shipping is already included.",
    emailCopy: "Hi William, the Outdoor Backpack in your cart is nearly sold out in this colorway! Secure today. As a bonus, your order of $130 qualifies for free shipping automatically.",
    createdAt: new Date(Date.now() - 3 * 3600000),
  },
  {
    email: "olivia.p@gmail.com",
    cartValue: 95.00,
    productName: "Silk Pillowcase",
    customerTier: "Gold",
    frictionPoint: "Trust",
    strategy: "Social Proof",
    status: "Converted",
    confidenceScore: 0.86,
    agentLog: "Gold customer, cart value $95.00. Selected 'Social Proof' highlighting dermatological approval and beauty awards to solve trust friction.",
    emailCopy: "Hi Olivia, we have saved your Silk Pillowcase. Recommended by top dermatologists for skin and hair health, and featured in Vogue Beauty. Sleep in luxury starting this week!",
    createdAt: new Date(Date.now() - 5 * 3600000),
  }
];

async function seed() {
  console.log("Seeding database/mock file...");
  try {
    // Delete existing records
    await db.delete(carts);
    // Insert initial seeded records
    await db.insert(carts).values(initialCarts);
    console.log(`Successfully seeded ${initialCarts.length} attempts!`);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seed();
